### ISSUE TITLE
Terraform import blocks are a little confusing

### ISSUE THREAD

**Issue by tcaddy** [enflow/terraform-provider-redirectpizza#21]
When I try to use the new [`import {}` blocks ](https://developer.hashicorp.com/terraform/language/import) in Terraform v1.5+, I get an error at TFC during the plan phase:
```
Expected http status 200, received: 404
```

<img width="1546" alt="image" src="https://github.com/enflow/terraform-provider-redirectpizza/assets/280902/97bc1d9c-cd84-4a6e-b499-8702776d403e">

It turns out that I have to use the integer id from the URL for a given resource at the redirect.pizza website as the id for the `import` block.  I found this a little confusing so I'm putting it here for others to find.

**Comment by mbardelmeijer** [comment]
Agreed that this can be improved in the documentation! I will add a segment to the README.

I prefer not to have the `id` in the import block at all, although haven't found an elegant way to handle that. PR's are welcome if someone has a good solution for that 👍

**Comment by mbardelmeijer** [comment]
Added with https://github.com/enflow/terraform-provider-redirectpizza/commit/272aa280749565f1862fcf5c975e37ef875a1840
